wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.2
    start_time: 1677601967.368223
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 75
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 75
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.8.2
      5: 0.13.10
      6: 4.24.0
      8:
      - 5
alpha_c:
  desc: null
  value: '1.0'
attention_dim:
  desc: null
  value: '512'
batch_size:
  desc: null
  value: '32'
blank_context:
  desc: null
  value: false
blank_context_zeros:
  desc: null
  value: false
blank_img:
  desc: null
  value: false
context_cond:
  desc: null
  value: caption
context_encoder_type:
  desc: null
  value: roberta
context_model:
  desc: null
  value: revised
cudnn.benchmark:
  desc: null
  value: 'True'
data_folder:
  desc: null
  value: ../../../datasets/pew/parsed_data/caption_caption_randompew
data_name:
  desc: null
  value: wikipedia_1_min_word_freq
decoder_dim:
  desc: null
  value: '512'
decoder_lr:
  desc: null
  value: '0.0004'
device:
  desc: null
  value: cpu
dropout:
  desc: null
  value: '0.5'
emb_dim:
  desc: null
  value: '512'
encoder_lr:
  desc: null
  value: '0.0001'
fine_tune_encoder:
  desc: null
  value: 'False'
grad_clip:
  desc: null
  value: '5.0'
label_cond:
  desc: null
  value: caption
loss_function:
  desc: null
  value: CrossEntropyLoss()
nlg_type:
  desc: null
  value: resnet-lstm
randomized:
  desc: null
  value: none
run_dir:
  desc: null
  value: ./runs/20230228_082816
workers:
  desc: null
  value: '1'
